app:
  name: dummy_store
  code_path: ../../
  discovery:
    mode: modules
    modules:
      include:
        - app.user.model
        - app.user.use_cases
        - app.user.interface
        - app.address.model
        - app.address.interface
        - app.product.model
        - app.product.use_cases
        - app.product.interface
        - app.order.model
        - app.order.interface
        - app.order_item.model
        - app.order_item.interface
  rest:
    backend: fastapi
    title: Dummy Store API
    version: 0.1.0
    docs_url: /docs
    redoc_url: /redoc

metrics:
  enabled: ${oc.decode:${oc.env:METRICS_ENABLED,true}}
  path: ${oc.env:METRICS_PATH,/metrics}
